import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ArrowRightIcon } from '@/components/finpulse/icons';
import { Colors, Fonts } from '@/constants/finpulse-theme';
import { useAppState } from '@/contexts/app-state';

const DAY_OPTIONS: { value: number; label: string }[] = [
  { value: 1, label: '24 hours' },
  { value: 3, label: '3 days' },
  { value: 7, label: '1 week' },
  { value: 14, label: '2 weeks' },
  { value: 30, label: '1 month' },
];

export default function ProfileScreen() {
  const { toggles, toggleSetting, storiesRead, tickers, defaultDays, setDefaultDays, redoOnboarding } =
    useAppState();

  function cycleDefaultDays() {
    const idx = DAY_OPTIONS.findIndex((d) => d.value === defaultDays);
    const next = DAY_OPTIONS[(idx + 1) % DAY_OPTIONS.length];
    setDefaultDays(next.value);
  }

  const watchlistSize = tickers?.length ?? 10;
  const defaultDaysLabel = DAY_OPTIONS.find((d) => d.value === defaultDays)?.label ?? `${defaultDays} days`;

  const settingsRows: {
    key: string;
    name: string;
    hint: string;
    kind: 'toggle' | 'value';
    toggleKey?: keyof typeof toggles;
    value?: string;
    onPress?: () => void;
  }[] = [
    { key: 'digest', name: 'Morning digest', hint: 'Pushed at 8:00am on weekdays', kind: 'toggle', toggleKey: 'digest' },
    { key: 'quiet', name: 'Only tell me about big swings', hint: 'Mutes anything under ±0.20', kind: 'toggle', toggleKey: 'quiet' },
    { key: 'beginner', name: 'Explain the jargon', hint: 'Underlines terms and offers plain English', kind: 'toggle', toggleKey: 'beginner' },
    {
      key: 'window',
      name: 'Default window',
      hint: 'What every screen opens on',
      kind: 'value',
      value: defaultDaysLabel,
      onPress: cycleDefaultDays,
    },
    { key: 'sources', name: 'Sources', hint: 'Finnhub company + market news', kind: 'value', value: '2 feeds' },
    {
      key: 'model',
      name: 'Model',
      hint: 'FinBERT, confidence-weighted, 3-day half-life',
      kind: 'value',
      value: 'v1',
    },
  ];

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.header}>
        <Text style={styles.h2}>You</Text>
      </View>
      <ScrollView>
        <View style={styles.statsRow}>
          <View style={[styles.statCol, styles.statColBordered]}>
            <Text style={styles.statValue}>{storiesRead}</Text>
            <Text style={styles.statLabel}>STORIES READ</Text>
          </View>
          <View style={styles.statCol}>
            <Text style={styles.statValue}>{watchlistSize}</Text>
            <Text style={styles.statLabel}>TICKERS TRACKED</Text>
          </View>
        </View>

        {settingsRows.map((row) => (
          <View key={row.key} style={styles.settingRow}>
            <View style={{ flex: 1, gap: 3 }}>
              <Text style={styles.settingName}>{row.name}</Text>
              <Text style={styles.settingHint}>{row.hint}</Text>
            </View>
            {row.kind === 'toggle' ? (
              <Toggle on={toggles[row.toggleKey!]} onPress={() => toggleSetting(row.toggleKey!)} />
            ) : (
              <Pressable onPress={row.onPress} disabled={!row.onPress}>
                <Text style={styles.settingValue}>{row.value}</Text>
              </Pressable>
            )}
          </View>
        ))}

        <View style={styles.footer}>
          <Pressable onPress={redoOnboarding} style={styles.redoBtn}>
            <Text style={styles.redoText}>Redo my interests</Text>
            <ArrowRightIcon size={16} color={Colors.text} />
          </Pressable>
          <Text style={styles.disclaimer}>
            Sentiment is generated by FinBERT and is not financial advice.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

function Toggle({ on, onPress }: { on: boolean; onPress: () => void }) {
  return (
    <Pressable onPress={onPress} style={[styles.toggleTrack, { justifyContent: on ? 'flex-end' : 'flex-start', backgroundColor: on ? Colors.text : 'transparent' }]}>
      <View style={[styles.toggleKnob, { backgroundColor: on ? Colors.bg : Colors.text }]} />
    </Pressable>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 14, borderBottomWidth: 2, borderBottomColor: Colors.divider },
  h2: { fontFamily: Fonts.heading, fontSize: 30, color: Colors.text, letterSpacing: -0.5 },
  statsRow: { flexDirection: 'row', padding: 20, borderBottomWidth: 2, borderBottomColor: Colors.divider },
  statCol: { flex: 1, paddingLeft: 14 },
  statColBordered: { borderRightWidth: 2, borderRightColor: Colors.divider, paddingLeft: 0, paddingRight: 14 },
  statValue: { fontFamily: Fonts.heading, fontSize: 44, lineHeight: 44, color: Colors.text, letterSpacing: -1 },
  statLabel: { fontFamily: Fonts.heading, fontSize: 9, letterSpacing: 1.2, color: Colors.neutral600, marginTop: 4 },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 20,
    paddingVertical: 16,
    minHeight: 64,
    borderBottomWidth: 1,
    borderBottomColor: Colors.neutral300,
  },
  settingName: { fontFamily: Fonts.heading, fontSize: 14, color: Colors.text },
  settingHint: { fontFamily: Fonts.body, fontSize: 11, color: Colors.neutral600 },
  settingValue: { fontFamily: Fonts.heading, fontSize: 12, letterSpacing: 0.6, textTransform: 'uppercase', color: Colors.accentText },
  toggleTrack: { width: 52, height: 28, borderWidth: 2, borderColor: Colors.text, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 2 },
  toggleKnob: { width: 20, height: 20 },
  footer: { padding: 20, gap: 10 },
  redoBtn: {
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 2,
    borderColor: Colors.divider,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  redoText: { fontFamily: Fonts.heading, fontSize: 13, color: Colors.text },
  disclaimer: { fontFamily: Fonts.body, fontSize: 11, lineHeight: 16, color: Colors.neutral600 },
});
